In [1]:
import pandas as pd

In [6]:
df = pd.read_csv("data/SN7577.tab", sep="\t")

In [7]:
df

,Q1,Q2,Q3,Q4,Q5ai,Q5aii,Q5aiii,Q5aiv,Q5av,Q5avi,...,numhhd,numkid,numkid2,numkid31,numkid32,numkid33,numkid34,numkid35,numkid36,wts
0,1,-1,1,8,0,0,0,1,0,0,...,3,11,2,0,0,0,0,1,0,1.11439
1,3,-1,1,4,0,0,0,0,0,0,...,3,11,2,0,0,0,0,1,0,2.56604
2,10,3,2,6,0,0,0,0,0,0,...,2,11,2,0,0,0,0,1,0,2.04468
3,9,-1,10,10,0,0,0,0,0,0,...,1,-1,2,0,0,0,0,1,0,1.07592
4,10,2,6,1,0,0,0,1,0,0,...,1,-1,2,0,0,0,0,1,0,1.25068
5,1,-1,1,1,0,0,0,0,0,0,...,2,-1,2,0,0,0,0,1,0,0.85126
6,1,-1,1,8,0,0,0,0,0,0,...,2,-1,2,0,0,0,0,1,0,1.51383
7,1,-1,1,1,0,0,0,0,0,0,...,2,-1,2,0,0,0,0,1,0,0.86168
8,9,-1,10,10,0,0,0,0,0,0,...,2,11,2,0,0,0,0,1,0,0.48973
9,2,-1,1,1,0,0,0,0,0,0,...,1,-1,2,0,0,0,0,1,0,0.36381
10,4,-1,1,1,1,0,1,0,0,1,...,2,-1,2,0,0,0,0,1,0,0.37077
11,1,-1,2,4,0,0,0,0,0,0,...,2,-1,2,0,0,0,0,1,0,2.08450
12,10,2,9,9,0,0,0,0,0,1,...,5,4,1,0,0,1,1,0,0,1.60022
13,11,11,1,1,0,0,0,0,0,0,...,1,-1,2,0,0,0,0,1,0,1.45152
14,1,-1,1,3,0,0,0,0,0,1,...,2,-1,2,0,0,0,0,1,0,0.40854
15,2,-1,1,3,1,0,0,0,0,0,...,2,11,2,0,0,0,0,1,0,0.85808
16,10,10,1,1,0,0,0,0,0,0,...,2,-1,2,0,0,0,0,1,0,1.65617
17,2,-1,2,3,0,0,0,0,0,0,...,1,-1,2,0,0,0,0,1,0,1.01381
18,2,-1,6,10,0,0,0,0,0,0,...,3,1,1,1,0,0,0,0,0,1.17951
19,2,-1,3,8,0,0,0,1,1,0,...,4,11,2,0,0,0,0,1,0,0.80929
20,10,2,2,3,0,0,0,0,0,0,...,2,-1,2,0,0,0,0,1,0,0.62783
21,9,-1,10,10,0,0,0,0,0,0,...,1,-1,2,0,0,0,0,1,0,0.65354
22,11,11,4,1,0,0,0,0,0,0,...,5,3,1,0,0,1,1,0,0,0.45708
23,10,1,1,1,0,0,0,0,1,0,...,2,-1,2,0,0,0,0,1,0,0.47963
24,1,-1,2,10,0,0,0,0,0,0,...,4,2,1,1,0,0,1,0,0,0.61752
25,2,-1,1,6,0,0,0,0,0,1,...,3,11,2,0,0,0,0,1,0,1.35928
26,1,-1,2,1,0,0,1,1,0,1,...,2,-1,2,0,0,0,0,1,0,1.69181
27,2,-1,4,5,0,0,0,0,0,0,...,2,-1,2,0,0,0,0,1,0,0.74933
28,2,-1,5,6,0,0,0,0,0,0,...,5,2,1,1,1,0,0,0,0,0.61461
29,1,-1,4,5,0,0,0,0,1,0,...,2,-1,2,0,0,0,0,1,0,1.59242
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1256,9,-1,8,6,0,0,0,0,0,0,...,4,2,1,0,1,0,0,0,0,1.30323
1257,11,1,1,1,0,0,0,0,0,0,...,1,-1,2,0,0,0,0,1,0,0.85431
1258,2,-1,6,1,0,0,0,0,0,0,...,2,11,2,0,0,0,0,1,0,4.48015
1259,2,-1,2,3,0,0,0,0,0,0,...,6,11,2,0,0,0,0,1,0,0.29368
1260,1,-1,1,5,0,0,0,0,0,0,...,3,1,1,0,1,0,0,0,0,1.53077
1261,3,-1,1,1,0,0,1,0,0,1,...,5,11,2,0,0,0,0,1,0,1.48170
1262,1,-1,7,7,0,0,0,1,0,0,...,4,11,2,0,0,0,0,1,0,0.79911
1263,5,-1,1,1,1,1,0,1,1,0,...,2,-1,2,0,0,0,0,1,0,1.65123
1264,10,10,10,10,0,0,0,0,0,0,...,5,11,2,0,0,0,0,1,0,1.29831
1265,2,-1,1,1,0,0,0,0,0,0,...,5,3,1,1,1,0,1,0,0,1.58842
1266,2,-1,1,1,0,0,0,0,0,0,...,3,11,2,0,0,0,0,1,0,1.73196
1267,4,-1,3,4,0,0,0,1,0,1,...,1,-1,2,0,0,0,0,1,0,0.57340
1268,2,-1,4,4,0,0,0,0,0,1,...,1,-1,2,0,0,0,0,1,0,0.45117
1269,11,11,11,12,0,0,0,0,0,0,...,1,-1,2,0,0,0,0,1,0,1.18764
1270,10,2,3,3,1,0,0,0,0,0,...,1,-1,2,0,0,0,0,1,0,0.66939
1271,2,-1,1,6,0,0,0,0,0,0,...,2,-1,2,0,0,0,0,1,0,0.44399
1272,1,-1,1,5,0,0,0,0,0,0,...,2,-1,2,0,0,0,0,1,0,0.81670
1273,3,-1,4,5,0,0,0,0,0,0,...,2,-1,2,0,0,0,0,1,0,0.70474
1274,2,-1,3,6,0,0,0,0,0,0,...,2,-1,2,0,0,0,0,1,0,0.86370
1275,10,2,4,7,0,0,0,0,0,0,...,3,1,1,1,0,0,0,0,0,1.06163
1276,10,10,4,6,0,0,0,0,0,0,...,3,11,2,0,0,0,0,1,0,0.88358
1277,2,-1,5,4,0,0,0,0,0,0,...,3,1,1,0,0,1,0,0,0,0.99600
1278,2,-1,4,5,0,0,0,0,0,0,...,4,2,1,0,0,0,1,0,0,0.82948
1279,1,-1,2,3,0,0,0,0,0,0,...,1,-1,2,0,0,0,0,1,0,0.87891
1280,10,2,3,4,0,0,0,0,1,0,...,4,2,1,1,0,0,0,0,0,0.59792
1281,2,-1,3,6,0,0,0,0,0,0,...,2,-1,2,0,0,0,0,1,0,0.85231
1282,10,10,2,10,0,0,0,0,0,0,...,1,-1,2,0,0,0,0,1,0,2.30831
1283,9,-1,8,9,0,0,0,0,0,0,...,4,2,1,1,0,0,0,0,0,2.84823
1284,11,11,1,2,0,0,0,1,1,0,...,2,-1,2,0,0,0,0,1,0,3.45887
1285,10,6,6,6,0,0,0,0,0,0,...,2,-1,2,0,0,0,0,1,0,1.94413

In [8]:
type(df)

pandas.core.frame.DataFrame

In [16]:
df.head()

,Q1,Q2,Q3,Q4,Q5ai,Q5aii,Q5aiii,Q5aiv,Q5av,Q5avi,...,numhhd,numkid,numkid2,numkid31,numkid32,numkid33,numkid34,numkid35,numkid36,wts
0,1,-1,1,8,0,0,0,1,0,0,...,3,11,2,0,0,0,0,1,0,1.11439
1,3,-1,1,4,0,0,0,0,0,0,...,3,11,2,0,0,0,0,1,0,2.56604
2,10,3,2,6,0,0,0,0,0,0,...,2,11,2,0,0,0,0,1,0,2.04468
3,9,-1,10,10,0,0,0,0,0,0,...,1,-1,2,0,0,0,0,1,0,1.07592
4,10,2,6,1,0,0,0,1,0,0,...,1,-1,2,0,0,0,0,1,0,1.25068

In [10]:
df.tail()

,Q1,Q2,Q3,Q4,Q5ai,Q5aii,Q5aiii,Q5aiv,Q5av,Q5avi,...,numhhd,numkid,numkid2,numkid31,numkid32,numkid33,numkid34,numkid35,numkid36,wts
1281,2,-1,3,6,0,0,0,0,0,0,...,2,-1,2,0,0,0,0,1,0,0.85231
1282,10,10,2,10,0,0,0,0,0,0,...,1,-1,2,0,0,0,0,1,0,2.30831
1283,9,-1,8,9,0,0,0,0,0,0,...,4,2,1,1,0,0,0,0,0,2.84823
1284,11,11,1,2,0,0,0,1,1,0,...,2,-1,2,0,0,0,0,1,0,3.45887
1285,10,6,6,6,0,0,0,0,0,0,...,2,-1,2,0,0,0,0,1,0,1.94413

In [17]:
len(df)

1286

In [18]:
df.columns

Index(['Q1', 'Q2', 'Q3', 'Q4', 'Q5ai', 'Q5aii', 'Q5aiii', 'Q5aiv', 'Q5av',
       'Q5avi',
       ...
       'numhhd', 'numkid', 'numkid2', 'numkid31', 'numkid32', 'numkid33',
       'numkid34', 'numkid35', 'numkid36', 'wts'],
      dtype='object', length=202)

In [26]:
for column_name in df.columns:
    print(column_name)

Q1
Q2
Q3
Q4
Q5ai
Q5aii
Q5aiii
Q5aiv
Q5av
Q5avi
Q5avii
Q5aviii
Q5aix
Q5ax
Q5axi
Q5axii
Q5axiii
Q5axiv
Q5axv
Q5bi
Q5bii
Q5biii
Q5biv
Q5bv
Q5bvi
Q5bvii
Q5bviii
Q5bix
Q5bx
Q5bxi
Q5bxii
Q5bxiii
Q5bxiv
Q5bxv
Q6
Q7a
Q7b
Q8
Q9
Q10a
Q10b
Q10c
Q10d
Q11a
Q11b
Q12a
Q12b
Q13i
Q13ii
Q13iii
Q13iv
Q14
Q15
Q16a
Q16b
Q16c
Q16d
Q16e
Q16f
Q16g
Q16h
Q17a
Q17b
Q17c
Q17d
Q17e
Q17f
Q17g
Q18ai
Q18aii
Q18aiii
Q18aiv
Q18av
Q18avi
Q18avii
Q18aviii
Q18aix
Q18bi
Q18bii
Q18biii
Q18biv
Q18bv
Q18bvi
Q18bvii
Q18bviii
Q18bix
Q19a
Q19b
Q19c
Q19d
access1
access2
access3
access4
access5
access6
access7
web1
web2
web3
web4
web5
web6
web7
web8
web9
web10
web11
web12
web13
web14
web15
web16
web17
web18
dbroad
intten
netfq
daily1
daily2
daily3
daily4
daily5
daily6
daily7
daily8
daily9
daily10
daily11
daily12
daily13
daily14
daily15
daily16
daily17
daily18
daily19
daily20
daily21
daily22
daily23
daily24
daily25
sunday1
sunday2
sunday3
sunday4
sunday5
sunday6
sunday7
sunday8
sunday9
sunday10
sunday11
sunday12
sunday13
sunday14
sunday15
sunday16
sunday17
sunday18
sunday19
sunday20
press1
press2
broadsheet1
broadsheet2
broadsheet3
popular1
popular2
popular3
popular4
popular5
sex
age
agegroups
numage
class
sgrade
work
gor
qual
ethnic
ethnicity
party
cie
wrkcie
income
tenure
tennet
lstage
maritl
numhhd
numkid
numkid2
numkid31
numkid32
numkid33
numkid34
numkid35
numkid36
wts

# %load code/dfinfo
When we asked for the column names and their datatypes, the output was abridged, i.e. we didn't get the values for all of the columns. Can you write a small piece of code which will return all of the values

Challenge: Modify your program to output both the name and the dataype for each column. (hint: use help on the builtin `zip()` function)

In [27]:
df.shape

(1286, 202)

In [31]:
columns_used = [0,1,2,173,174,175]

In [34]:
df_some_cols = pd.read_csv("data/SN7577.tab", sep="\t", usecols=[0,1,2,173,174,175])

In [35]:
df_some_cols = pd.read_csv("data/SN7577.tab", sep="\t", usecols=columns_used)

In [36]:
df_some_cols

      Q1  Q2  Q3  sex  age  agegroups
0      1  -1   1    2    6          5
1      3  -1   1    1    2          2
2     10   3   2    2    7          7
3      9  -1  10    2    4          4
4     10   2   6    1    4          4
5      1  -1   1    2    4          4
6      1  -1   1    2    7          6
7      1  -1   1    2    7          7
8      9  -1  10    2    7          6
9      2  -1   1    1    6          5
10     4  -1   1    1    6          5
11     1  -1   2    1    4          4
12    10   2   9    2    3          3
13    11  11   1    2    7          7
14     1  -1   1    2    7          6
15     2  -1   1    2    7          6
16    10  10   1    2    3          3
17     2  -1   2    1    4          4
18     2  -1   6    2    2          2
19     2  -1   3    2    1          1
20    10   2   2    1    7          6
21     9  -1  10    2    7          6
22    11  11   4    2    4          4
23    10   1   1    2    7          6
24     1  -1   2    2    2          2
25     2  -1   1    2    4          4
26     1  -1   2    2    6          5
27     2  -1   4    2    7          7
28     2  -1   5    1    5          5
29     1  -1   4    2    4          4
...   ..  ..  ..  ...  ...        ...
1256   9  -1   8    1    4          4
1257  11   1   1    1    7          6
1258   2  -1   6    1    2          2
1259   2  -1   2    1    3          3
1260   1  -1   1    2    3          3
1261   3  -1   1    2    5          5
1262   1  -1   7    1    1          1
1263   5  -1   1    2    3          3
1264  10  10  10    2    1          1
1265   2  -1   1    1    3          3
1266   2  -1   1    1    4          4
1267   4  -1   3    2    7          6
1268   2  -1   4    1    7          7
1269  11  11  11    1    3          3
1270  10   2   3    2    7          6
1271   2  -1   1    1    7          6
1272   1  -1   1    2    6          5
1273   3  -1   4    2    6          5
1274   2  -1   3    1    3          3
1275  10   2   4    1    3          3
1276  10  10   4    2    4          4
1277   2  -1   5    2    2          2
1278   2  -1   4    2    3          3
1279   1  -1   2    2    3          3
1280  10   2   3    1    3          3
1281   2  -1   3    1    2          2
1282  10  10   2    2    7          6
1283   9  -1   8    1    1          1
1284  11  11   1    1    6          5
1285  10   6   6    1    7          6

[1286 rows x 6 columns]

In [38]:
df_some_cols['Q1']

0        1
1        3
2       10
3        9
4       10
5        1
6        1
7        1
8        9
9        2
10       4
11       1
12      10
13      11
14       1
15       2
16      10
17       2
18       2
19       2
20      10
21       9
22      11
23      10
24       1
25       2
26       1
27       2
28       2
29       1
        ..
1256     9
1257    11
1258     2
1259     2
1260     1
1261     3
1262     1
1263     5
1264    10
1265     2
1266     2
1267     4
1268     2
1269    11
1270    10
1271     2
1272     1
1273     3
1274     2
1275    10
1276    10
1277     2
1278     2
1279     1
1280    10
1281     2
1282    10
1283     9
1284    11
1285    10
Name: Q1, Length: 1286, dtype: int64

In [39]:
df_some_cols[ ["Q1", "Q2"] ]

      Q1  Q2
0      1  -1
1      3  -1
2     10   3
3      9  -1
4     10   2
5      1  -1
6      1  -1
7      1  -1
8      9  -1
9      2  -1
10     4  -1
11     1  -1
12    10   2
13    11  11
14     1  -1
15     2  -1
16    10  10
17     2  -1
18     2  -1
19     2  -1
20    10   2
21     9  -1
22    11  11
23    10   1
24     1  -1
25     2  -1
26     1  -1
27     2  -1
28     2  -1
29     1  -1
...   ..  ..
1256   9  -1
1257  11   1
1258   2  -1
1259   2  -1
1260   1  -1
1261   3  -1
1262   1  -1
1263   5  -1
1264  10  10
1265   2  -1
1266   2  -1
1267   4  -1
1268   2  -1
1269  11  11
1270  10   2
1271   2  -1
1272   1  -1
1273   3  -1
1274   2  -1
1275  10   2
1276  10  10
1277   2  -1
1278   2  -1
1279   1  -1
1280  10   2
1281   2  -1
1282  10  10
1283   9  -1
1284  11  11
1285  10   6

[1286 rows x 2 columns]

In [49]:
type(df_some_cols[ ["Q1", "Q2"] ])

pandas.core.frame.DataFrame

In [50]:
col_list = "Q1"

In [51]:
df_some_cols[col_list]

0        1
1        3
2       10
3        9
4       10
5        1
6        1
7        1
8        9
9        2
10       4
11       1
12      10
13      11
14       1
15       2
16      10
17       2
18       2
19       2
20      10
21       9
22      11
23      10
24       1
25       2
26       1
27       2
28       2
29       1
        ..
1256     9
1257    11
1258     2
1259     2
1260     1
1261     3
1262     1
1263     5
1264    10
1265     2
1266     2
1267     4
1268     2
1269    11
1270    10
1271     2
1272     1
1273     3
1274     2
1275    10
1276    10
1277     2
1278     2
1279     1
1280    10
1281     2
1282    10
1283     9
1284    11
1285    10
Name: Q1, Length: 1286, dtype: int64

In [58]:
print(range(0,20,2))

range(0, 20, 2)

In [ ]:
df[ ]

In [60]:
type(range(0,20,2))

range

In [61]:
list(range(0,20,2))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [65]:
df[0:4]

,Q1,Q2,Q3,Q4,Q5ai,Q5aii,Q5aiii,Q5aiv,Q5av,Q5avi,...,numhhd,numkid,numkid2,numkid31,numkid32,numkid33,numkid34,numkid35,numkid36,wts
0,1,-1,1,8,0,0,0,1,0,0,...,3,11,2,0,0,0,0,1,0,1.11439
1,3,-1,1,4,0,0,0,0,0,0,...,3,11,2,0,0,0,0,1,0,2.56604
2,10,3,2,6,0,0,0,0,0,0,...,2,11,2,0,0,0,0,1,0,2.04468
3,9,-1,10,10,0,0,0,0,0,0,...,1,-1,2,0,0,0,0,1,0,1.07592

In [68]:
df_some_cols.query("sex == 1")

      Q1  Q2  Q3  sex  age  agegroups
1      3  -1   1    1    2          2
4     10   2   6    1    4          4
9      2  -1   1    1    6          5
10     4  -1   1    1    6          5
11     1  -1   2    1    4          4
17     2  -1   2    1    4          4
20    10   2   2    1    7          6
28     2  -1   5    1    5          5
30     9  -1  10    1    5          5
34     6  -1   1    1    1          1
36     3  -1   1    1    6          5
38    10   1   6    1    5          5
40     2  -1   1    1    6          5
41     1  -1   1    1    7          6
44     2  -1   2    1    3          3
48     2  -1   3    1    2          2
49     2  -1   1    1    2          2
50    10   2   4    1    2          2
51     2  -1   2    1    7          6
54     4  -1   6    1    7          7
55     9  -1   7    1    1          1
56     1  -1   2    1    7          6
60    10   2   8    1    7          6
61     1  -1   1    1    7          6
64     6  -1   1    1    7          6
65     2  -1   1    1    7          6
69    11  11   1    1    3          3
70     3  -1   1    1    7          7
73     2  -1   1    1    3          3
74    10   6   1    1    7          6
...   ..  ..  ..  ...  ...        ...
1238   2  -1   4    1    2          2
1239   2  -1   1    1    1          1
1240  10   2   1    1    7          7
1241   1  -1   1    1    6          5
1242   2  -1   1    1    5          5
1244   2  -1   4    1    4          4
1245   2  -1   1    1    4          4
1248   3  -1   3    1    1          1
1249  10   1   1    1    7          6
1250  10   2   4    1    1          1
1252   2  -1   1    1    4          4
1253   9  -1  10    1    1          1
1255   5  -1   1    1    1          1
1256   9  -1   8    1    4          4
1257  11   1   1    1    7          6
1258   2  -1   6    1    2          2
1259   2  -1   2    1    3          3
1262   1  -1   7    1    1          1
1265   2  -1   1    1    3          3
1266   2  -1   1    1    4          4
1268   2  -1   4    1    7          7
1269  11  11  11    1    3          3
1271   2  -1   1    1    7          6
1274   2  -1   3    1    3          3
1275  10   2   4    1    3          3
1280  10   2   3    1    3          3
1281   2  -1   3    1    2          2
1283   9  -1   8    1    1          1
1284  11  11   1    1    6          5
1285  10   6   6    1    7          6

[655 rows x 6 columns]

In [70]:
df_over5 = df_some_cols.query("age > 5")

In [71]:
df_over5

      Q1  Q2  Q3  sex  age  agegroups
0      1  -1   1    2    6          5
2     10   3   2    2    7          7
6      1  -1   1    2    7          6
7      1  -1   1    2    7          7
8      9  -1  10    2    7          6
9      2  -1   1    1    6          5
10     4  -1   1    1    6          5
13    11  11   1    2    7          7
14     1  -1   1    2    7          6
15     2  -1   1    2    7          6
20    10   2   2    1    7          6
21     9  -1  10    2    7          6
23    10   1   1    2    7          6
26     1  -1   2    2    6          5
27     2  -1   4    2    7          7
32    10   1   6    2    6          5
33     1  -1   1    2    7          6
36     3  -1   1    1    6          5
39     1  -1   1    2    7          7
40     2  -1   1    1    6          5
41     1  -1   1    1    7          6
51     2  -1   2    1    7          6
52     4  -1   1    2    7          6
54     4  -1   6    1    7          7
56     1  -1   2    1    7          6
60    10   2   8    1    7          6
61     1  -1   1    1    7          6
62    10   2   1    2    7          6
64     6  -1   1    1    7          6
65     2  -1   1    1    7          6
...   ..  ..  ..  ...  ...        ...
1178   1  -1   1    2    6          5
1181  10  11   1    1    7          7
1186   2  -1   7    2    7          6
1188  10   3   1    2    7          6
1189   1  -1   1    2    6          5
1190   1  -1   1    1    7          7
1203  10   9  10    2    7          7
1206   6  -1   1    1    7          6
1211   9  -1  10    1    6          5
1222   2  -1   1    1    7          6
1223   2  -1   4    2    6          5
1225   9  -1  10    1    7          7
1226   8  -1   1    2    7          6
1228   1  -1   2    1    7          7
1229   1  -1   1    1    6          5
1231   9  -1   8    2    7          7
1240  10   2   1    1    7          7
1241   1  -1   1    1    6          5
1243   2  -1   6    2    6          5
1249  10   1   1    1    7          6
1257  11   1   1    1    7          6
1267   4  -1   3    2    7          6
1268   2  -1   4    1    7          7
1270  10   2   3    2    7          6
1271   2  -1   1    1    7          6
1272   1  -1   1    2    6          5
1273   3  -1   4    2    6          5
1282  10  10   2    2    7          6
1284  11  11   1    1    6          5
1285  10   6   6    1    7          6

[411 rows x 6 columns]

In [73]:
df_over5_male = df_some_cols.query("age > 5 & sex == 1")

In [74]:
df_over5_male

      Q1  Q2  Q3  sex  age  agegroups
9      2  -1   1    1    6          5
10     4  -1   1    1    6          5
20    10   2   2    1    7          6
36     3  -1   1    1    6          5
40     2  -1   1    1    6          5
41     1  -1   1    1    7          6
51     2  -1   2    1    7          6
54     4  -1   6    1    7          7
56     1  -1   2    1    7          6
60    10   2   8    1    7          6
61     1  -1   1    1    7          6
64     6  -1   1    1    7          6
65     2  -1   1    1    7          6
70     3  -1   1    1    7          7
74    10   6   1    1    7          6
75    10   1   5    1    7          7
83     2  -1   1    1    7          7
86     1  -1   1    1    7          6
98     1  -1   1    1    7          7
106    2  -1   1    1    7          6
113    1  -1   1    1    7          6
114    2  -1   1    1    7          6
123    2  -1   1    1    7          7
138   10  10   6    1    7          6
155   10   1   1    1    7          6
163    2  -1   1    1    7          7
167    2  -1   1    1    7          6
180    1  -1   1    1    7          7
184    2  -1   2    1    7          7
206   10  10   2    1    6          5
...   ..  ..  ..  ...  ...        ...
1100   4  -1   1    1    7          6
1106   2  -1   1    1    7          7
1109   1  -1   2    1    7          6
1113   3  -1   1    1    7          6
1130  10  10   1    1    6          5
1135   1  -1   1    1    7          7
1138   3  -1   2    1    7          6
1141  10   2   6    1    7          6
1142   1  -1   1    1    7          6
1143  10   6  10    1    6          5
1146   1  -1   1    1    7          6
1150   1  -1   1    1    7          7
1156  10   5   1    1    6          5
1167   2  -1   1    1    7          7
1181  10  11   1    1    7          7
1190   1  -1   1    1    7          7
1206   6  -1   1    1    7          6
1211   9  -1  10    1    6          5
1222   2  -1   1    1    7          6
1225   9  -1  10    1    7          7
1228   1  -1   2    1    7          7
1229   1  -1   1    1    6          5
1240  10   2   1    1    7          7
1241   1  -1   1    1    6          5
1249  10   1   1    1    7          6
1257  11   1   1    1    7          6
1268   2  -1   4    1    7          7
1271   2  -1   1    1    7          6
1284  11  11   1    1    6          5
1285  10   6   6    1    7          6

[229 rows x 6 columns]

In [80]:
df.sample(10, random_state=10)

,Q1,Q2,Q3,Q4,Q5ai,Q5aii,Q5aiii,Q5aiv,Q5av,Q5avi,...,numhhd,numkid,numkid2,numkid31,numkid32,numkid33,numkid34,numkid35,numkid36,wts
374,2,-1,7,8,0,0,0,0,0,0,...,4,2,1,0,0,0,1,0,0,0.28741
1014,10,1,1,4,0,0,0,0,0,1,...,1,-1,2,0,0,0,0,1,0,1.15960
668,2,-1,3,9,0,0,0,1,0,1,...,3,1,1,1,0,0,0,0,0,1.29831
672,9,-1,8,9,0,0,0,0,0,0,...,1,-1,2,0,0,0,0,1,0,0.94704
123,2,-1,1,1,0,0,0,0,0,0,...,1,-1,2,0,0,0,0,1,0,0.72481
1051,2,-1,6,6,0,0,0,0,0,0,...,4,2,1,1,1,0,0,0,0,0.82424
943,10,10,11,11,0,0,0,0,0,0,...,2,11,2,0,0,0,0,1,0,0.30967
305,2,-1,2,1,1,0,0,0,0,0,...,5,11,2,0,0,0,0,1,0,0.36160
7,1,-1,1,1,0,0,0,0,0,0,...,2,-1,2,0,0,0,0,1,0,0.86168
326,1,-1,6,7,0,0,0,0,0,0,...,5,11,2,0,0,0,0,1,0,0.54185

In [81]:
df.sample(frac=0.1, random_state=10)

,Q1,Q2,Q3,Q4,Q5ai,Q5aii,Q5aiii,Q5aiv,Q5av,Q5avi,...,numhhd,numkid,numkid2,numkid31,numkid32,numkid33,numkid34,numkid35,numkid36,wts
374,2,-1,7,8,0,0,0,0,0,0,...,4,2,1,0,0,0,1,0,0,0.28741
1014,10,1,1,4,0,0,0,0,0,1,...,1,-1,2,0,0,0,0,1,0,1.15960
668,2,-1,3,9,0,0,0,1,0,1,...,3,1,1,1,0,0,0,0,0,1.29831
672,9,-1,8,9,0,0,0,0,0,0,...,1,-1,2,0,0,0,0,1,0,0.94704
123,2,-1,1,1,0,0,0,0,0,0,...,1,-1,2,0,0,0,0,1,0,0.72481
1051,2,-1,6,6,0,0,0,0,0,0,...,4,2,1,1,1,0,0,0,0,0.82424
943,10,10,11,11,0,0,0,0,0,0,...,2,11,2,0,0,0,0,1,0,0.30967
305,2,-1,2,1,1,0,0,0,0,0,...,5,11,2,0,0,0,0,1,0,0.36160
7,1,-1,1,1,0,0,0,0,0,0,...,2,-1,2,0,0,0,0,1,0,0.86168
326,1,-1,6,7,0,0,0,0,0,0,...,5,11,2,0,0,0,0,1,0,0.54185
593,9,-1,6,10,0,0,0,0,1,1,...,2,-1,2,0,0,0,0,1,0,0.98477
378,2,-1,1,8,1,0,0,0,0,0,...,2,-1,2,0,0,0,0,1,0,0.80346
763,4,-1,1,5,1,0,0,1,0,0,...,2,-1,2,0,0,0,0,1,0,0.47400
596,10,10,3,3,0,1,0,0,0,1,...,2,-1,2,0,0,0,0,1,0,0.65246
188,11,10,11,1,0,0,0,0,0,0,...,3,1,1,0,0,1,0,0,0,0.89269
74,10,6,1,10,0,1,1,1,1,1,...,2,-1,2,0,0,0,0,1,0,0.82697
370,10,3,4,5,0,0,0,0,0,1,...,3,11,2,0,0,0,0,1,0,0.66217
758,10,1,1,10,0,0,0,0,0,1,...,2,-1,2,0,0,0,0,1,0,0.56413
67,11,3,6,7,0,0,0,0,0,1,...,1,-1,2,0,0,0,0,1,0,0.57945
988,10,10,1,1,1,0,0,0,0,0,...,2,-1,2,0,0,0,0,1,0,0.64833
143,1,-1,2,2,0,0,0,0,0,0,...,5,11,2,0,0,0,0,1,0,0.99009
273,2,-1,5,4,0,0,0,0,0,0,...,3,11,2,0,0,0,0,1,0,1.19421
504,2,-1,1,3,0,0,0,1,0,0,...,1,-1,2,0,0,0,0,1,0,0.74993
482,2,-1,6,10,0,0,0,0,0,0,...,4,3,1,0,0,1,1,0,0,0.44274
365,1,-1,1,1,0,0,0,0,0,0,...,1,-1,2,0,0,0,0,1,0,0.33869
381,4,-1,1,1,0,0,0,0,1,0,...,2,-1,2,0,0,0,0,1,0,0.35829
428,1,-1,1,10,0,0,0,0,0,0,...,5,3,1,0,0,1,1,0,0,1.25233
891,2,-1,1,1,1,0,0,0,1,1,...,1,-1,2,0,0,0,0,1,0,1.64450
691,3,-1,1,1,0,0,0,0,0,1,...,3,11,2,0,0,0,0,1,0,0.83253
244,9,-1,10,3,0,0,0,0,0,0,...,1,-1,2,0,0,0,0,1,0,1.52921
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383,1,-1,1,3,0,0,0,0,0,1,...,2,-1,2,0,0,0,0,1,0,1.08211
809,2,-1,2,5,0,0,0,0,1,1,...,4,2,1,0,0,1,0,0,0,2.46972
971,2,-1,1,1,0,0,0,0,0,0,...,2,-1,2,0,0,0,0,1,0,1.86365
510,9,-1,10,10,0,0,0,0,0,0,...,3,2,1,1,0,0,0,0,0,0.43567
836,9,-1,10,10,0,0,0,0,0,1,...,3,1,1,1,0,0,0,0,0,1.02398
1166,4,-1,1,1,0,0,0,1,0,0,...,2,-1,2,0,0,0,0,1,0,0.97642
102,2,-1,2,6,0,0,0,0,0,0,...,3,11,2,0,0,0,0,1,0,0.57863
392,2,-1,4,10,0,0,0,0,0,0,...,1,-1,2,0,0,0,0,1,0,1.99592
1160,10,10,6,9,0,0,0,0,1,1,...,3,1,1,0,1,0,0,0,0,0.91437
1277,2,-1,5,4,0,0,0,0,0,0,...,3,1,1,0,0,1,0,0,0,0.99600
43,10,10,1,1,0,0,0,0,0,0,...,4,1,1,0,0,0,1,0,0,1.70814
858,9,-1,10,10,0,0,0,0,0,0,...,3,1,1,0,1,0,0,0,0,1.74674
520,3,-1,1,4,0,0,0,0,0,0,...,3,11,2,0,0,0,0,1,0,2.87802
1027,9,-1,10,11,0,0,0,0,0,0,...,5,11,2,0,0,0,0,1,0,1.04948
307,3,-1,3,4,0,0,0,0,0,0,...,4,1,1,1,0,0,0,0,0,0.60531
245,11,10,1,6,0,0,1,1,1,1,...,3,1,1,0,0,0,1,0,0,1.06000
441,6,-1,1,6,0,0,0,0,0,1,...,2,-1,2,0,0,0,0,1,0,1.04662
879,1,-1,3,9,0,0,0,0,0,0,...,2,-1,2,0,0,0,0,1,0,0.99853
982,2,-1,1,9,0,0,0,0,0,0,...,3,11,2,0,0,0,0,1,0,0.21992
795,1,-1,1,1,0,0,0,1,0,0,...,1,-1,2,0,0,0,0,1,0,0.38798
751,10,3,1,3,0,0,0,0,0,0,...,3,1,1,1,0,0,0,0,0,1.16775
411,5,-1,5,4,0,0,1,0,1,0,...,5,11,2,0,0,0,0,1,0,0.37159
573,1,-1,1,1,0,0,1,1,0,0,...,5,11,2,0,0,0,0,1,0,0.54037
738,10,10,1,9,0,0,0,0,0,0,...,5,2,1,0,0,0,1,0,0,0.57189
1127,10,10,3,8,0,0,0,0,0,0,...,6,11,2,0,0,0,0,1,0,0.41992
591,6,-1,1,10,0,0,0,0,0,0,...,2,-1,2,0,0,0,0,1,0,1.73513
419,7,-1,3,10,0,0,0,0,0,0,...,2,-1,2,0,0,0,0,1,0,1.57526
225,10,10,3,1,1,1,0,0,0,0,...,1,-1,2,0,0,0,0,1,0,0.79632
366,10,10,10,10,0,0,0,0,0,0,...,2,-1,2,0,0,0,0,1,0,0.93776
555,1,-1,1,10,0,0,0,0,1,1,...,4,2,1,0,0,0,1,0,0,1.82016